version: '3'

vars:
  GREETING: Hello, World!

tasks:
  cmake:
    cmds:
      - cmake -B build -S . -GNinja -DCMAKE_BUILD_TYPE=Release
  build:
    cmds:
      - cmake --build build
  run:
    cmds:
      - ./build/main
